import {
  convertDMMFToModels,
  processAllDirectives,
} from '@dee-wan/schema-parser'
import { DMMF } from '@prisma/generator-helper'
import { mkdir, writeFile } from 'fs/promises'
import { join, resolve } from 'path'
import { generateSQL } from '.'
import { setGlobalDialect } from './sql-builder-dialect'

interface GenerateConfig {
  dialect: 'postgres' | 'sqlite'
  skipInvalid: boolean
}

interface GenerateClientOptions {
  datamodel: DMMF.Datamodel
  outputDir: string
  config: GenerateConfig
}

export async function generateClient(options: GenerateClientOptions) {
  const { datamodel, outputDir, config } = options

  setGlobalDialect(config.dialect)

  const models = convertDMMFToModels(datamodel)

  const directiveResults = processAllDirectives(
    datamodel.models as unknown as DMMF.Model[],
    datamodel,
    {
      skipInvalid: config.skipInvalid,
    },
  )

  const queries = new Map<string, Map<string, Map<string, any>>>()

  for (const [modelName, result] of directiveResults) {
    if (result.directives.length === 0) continue

    if (!queries.has(modelName)) {
      queries.set(modelName, new Map())
    }

    const modelQueries = queries.get(modelName)!

    for (const directive of result.directives) {
      try {
        const method = directive.header // "findMany", "count", etc.
        const sqlDirective = generateSQL(directive)

        if (!modelQueries.has(method)) {
          modelQueries.set(method, new Map())
        }

        const methodQueries = modelQueries.get(method)!

        const queryKey = createQueryKey(directive.query.processed)

        methodQueries.set(queryKey, {
          sql: sqlDirective.sql,
          params: sqlDirective.staticParams,
          dynamicKeys: sqlDirective.dynamicKeys,
          paramMappings: sqlDirective.paramMappings,
        })
      } catch (error) {
        if (!config.skipInvalid) throw error
      }
    }
  }

  const absoluteOutputDir = resolve(process.cwd(), outputDir)
  await mkdir(absoluteOutputDir, { recursive: true })

  const code = generateCode(models, queries, config.dialect)
  const outputPath = join(absoluteOutputDir, 'index.ts')

  await writeFile(outputPath, code)

  const totalQueries = Array.from(queries.values()).reduce(
    (sum, methodMap) =>
      sum +
      Array.from(methodMap.values()).reduce(
        (s, queryMap) => s + queryMap.size,
        0,
      ),
    0,
  )
  console.log(`✓ Generated ${queries.size} models, ${totalQueries} queries`)
  console.log(`✓ Output: ${outputPath}`)
}

function createQueryKey(processedQuery: Record<string, unknown>): string {
  return JSON.stringify(processedQuery, (key, value) => {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      const sorted: Record<string, unknown> = {}
      for (const k of Object.keys(value).sort()) {
        sorted[k] = value[k]
      }
      return sorted
    }
    return value
  })
}

function generateCode(
  models: any[],
  queries: Map<string, Map<string, Map<string, any>>>,
  dialect: 'postgres' | 'sqlite',
): string {
  const cleanModels = models.map((model) => ({
    ...model,
    fields: model.fields.filter((f: any) => f !== undefined && f !== null),
  }))

  return `// Generated by @prisma-sql/generator - DO NOT EDIT
import { buildSQL, transformQueryResults, type PrismaMethod } from 'prisma-sql'

const MODELS = ${JSON.stringify(cleanModels, null, 2)}

const QUERIES: Record<string, Record<string, Record<string, {
  sql: string
  params: unknown[]
  dynamicKeys: string[]
  paramMappings: any[]
}>>> = ${formatQueries(queries)}

const DIALECT = ${JSON.stringify(dialect)}

function normalizeQuery(args: any): string {
  if (!args) return '{}'
  return JSON.stringify(args, (key, value) => {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      const sorted: Record<string, unknown> = {}
      for (const k of Object.keys(value).sort()) {
        sorted[k] = value[k]
      }
      return sorted
    }
    return value
  })
}

function extractDynamicParams(args: any, dynamicKeys: string[]): unknown[] {
  const params: unknown[] = []
  
  for (const key of dynamicKeys) {
    const parts = key.split(':')
    const path = parts[0].split('.')
    let value: any = args
    
    for (const part of path) {
      if (value === null || value === undefined) break
      value = value[part]
    }
    
    if (value === undefined) {
      throw new Error(\`Missing required parameter: \${key}\`)
    }
    
    params.push(value)
  }
  
  return params
}

async function executeQuery(client: any, sql: string, params: unknown[]): Promise<unknown[]> {
  if (DIALECT === 'postgres') {
    return await client.unsafe(sql, params)
  }
  
  const stmt = client.prepare(sql)
  
  if (sql.toUpperCase().includes('COUNT(*) AS')) {
    return [stmt.get(...params)]
  }
  
  return stmt.all(...params)
}

export function createExtension(config: {
  postgres?: any
  sqlite?: any
  debug?: boolean
  onQuery?: (info: {
    model: string
    method: string
    sql: string
    params: unknown[]
    duration: number
    prebaked: boolean
  }) => void
}) {
  const { postgres, sqlite, debug, onQuery } = config

  if (!postgres && !sqlite) {
    throw new Error('Extension requires postgres or sqlite client')
  }

  const client = postgres || sqlite
  const actualDialect = postgres ? 'postgres' : 'sqlite'

  if (actualDialect !== DIALECT) {
    throw new Error(\`Generated code is for \${DIALECT}, but you provided \${actualDialect}\`)
  }

  return (prisma: any) => {
    const handleMethod = async function(this: any, method: PrismaMethod, args: any) {
      const modelName = this?.name || this?.$name
      const startTime = Date.now()

      const queryKey = normalizeQuery(args)
      const prebakedQuery = QUERIES[modelName]?.[method]?.[queryKey]

      let sql: string
      let params: unknown[]
      let prebaked = false

      if (prebakedQuery) {
        sql = prebakedQuery.sql
        params = [...prebakedQuery.params, ...extractDynamicParams(args, prebakedQuery.dynamicKeys)]
        prebaked = true
      } else {
        const model = MODELS.find((m: any) => m.name === modelName)
        
        if (!model) {
          return this.$parent[modelName][method](args)
        }

        const result = buildSQL(model, MODELS, method, args, DIALECT)
        sql = result.sql
        params = result.params
      }

      if (debug) {
        console.log(\`[\${DIALECT}] \${modelName}.\${method} \${prebaked ? '⚡ PREBAKED' : '🔨 RUNTIME'}\`)
        console.log('SQL:', sql)
        console.log('Params:', params)
      }

      const results = await executeQuery(client, sql, params)
      const duration = Date.now() - startTime

      onQuery?.({
        model: modelName,
        method,
        sql,
        params,
        duration,
        prebaked,
      })

      return transformQueryResults(method, results)
    }

    return prisma.$extends({
      name: 'prisma-sql-generated',
      
      client: {
        $original: prisma,
      },

      model: {
        $allModels: {
          async findMany(args: any) {
            return handleMethod.call(this, 'findMany', args)
          },
          async findFirst(args: any) {
            return handleMethod.call(this, 'findFirst', args)
          },
          async findUnique(args: any) {
            return handleMethod.call(this, 'findUnique', args)
          },
          async count(args: any) {
            return handleMethod.call(this, 'count', args)
          },
          async aggregate(args: any) {
            return handleMethod.call(this, 'aggregate', args)
          },
          async groupBy(args: any) {
            return handleMethod.call(this, 'groupBy', args)
          },
        },
      },
    })
  }
}
`
}

function formatQueries(
  queries: Map<string, Map<string, Map<string, any>>>,
): string {
  if (queries.size === 0) {
    return '{}'
  }

  const modelEntries: string[] = []

  for (const [modelName, methodMap] of queries) {
    const methodEntries: string[] = []

    for (const [method, queryMap] of methodMap) {
      const queryEntries: string[] = []

      for (const [queryKey, query] of queryMap) {
        queryEntries.push(`    ${JSON.stringify(queryKey)}: {
      sql: ${JSON.stringify(query.sql)},
      params: ${JSON.stringify(query.params)},
      dynamicKeys: ${JSON.stringify(query.dynamicKeys)},
      paramMappings: ${JSON.stringify(query.paramMappings)},
    }`)
      }

      methodEntries.push(`    ${JSON.stringify(method)}: {
${queryEntries.join(',\n')}
    }`)
    }

    modelEntries.push(`  ${JSON.stringify(modelName)}: {
${methodEntries.join(',\n')}
  }`)
  }

  return `{
${modelEntries.join(',\n')}
}`
}
