// tests/e2e/helpers/datamodel.ts
import type { DMMF } from '@prisma/generator-helper'

export const datamodel: DMMF.Datamodel = {
  models: [
    {
      name: 'Organization',
      dbName: 'organizations',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'slug',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'plan',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'settings',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Json',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'updatedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: true,
        },
        {
          name: 'members',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Member',
          relationName: 'OrganizationMembers',
          relationFromFields: ['id'],
          relationToFields: ['organizationId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'projects',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Project',
          relationName: 'OrganizationProjects',
          relationFromFields: ['id'],
          relationToFields: ['organizationId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'User',
      dbName: 'users',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'email',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'avatarUrl',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'role',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'status',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'metadata',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Json',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'tags',
          kind: 'scalar',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'lastLoginAt',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'updatedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: true,
        },
        {
          name: 'memberships',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Member',
          relationName: 'UserMemberships',
          relationFromFields: ['id'],
          relationToFields: ['userId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'assignedTasks',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskAssignee',
          relationFromFields: ['id'],
          relationToFields: ['assigneeId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdTasks',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskCreator',
          relationFromFields: ['id'],
          relationToFields: ['creatorId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'comments',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Comment',
          relationName: 'UserComments',
          relationFromFields: ['id'],
          relationToFields: ['authorId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'activities',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Activity',
          relationName: 'UserActivities',
          relationFromFields: ['id'],
          relationToFields: ['userId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'notifications',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Notification',
          relationName: 'UserNotifications',
          relationFromFields: ['id'],
          relationToFields: ['userId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Member',
      dbName: 'members',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'role',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'joinedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'organizationId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'userId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'organization',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Organization',
          relationName: 'OrganizationMembers',
          relationFromFields: ['organizationId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'user',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'User',
          relationName: 'UserMemberships',
          relationFromFields: ['userId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Project',
      dbName: 'projects',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'description',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'color',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'status',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'isPublic',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Boolean',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'budget',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Decimal',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'startDate',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'endDate',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'metadata',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Json',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'updatedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: true,
        },
        {
          name: 'organizationId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'organization',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Organization',
          relationName: 'OrganizationProjects',
          relationFromFields: ['organizationId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'tasks',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'ProjectTasks',
          relationFromFields: ['id'],
          relationToFields: ['projectId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'labels',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Label',
          relationName: 'ProjectLabels',
          relationFromFields: ['id'],
          relationToFields: ['projectId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'milestones',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Milestone',
          relationName: 'ProjectMilestones',
          relationFromFields: ['id'],
          relationToFields: ['projectId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Milestone',
      dbName: 'milestones',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'description',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'dueDate',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'completedAt',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'projectId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'project',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Project',
          relationName: 'ProjectMilestones',
          relationFromFields: ['projectId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'tasks',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'MilestoneTasks',
          relationFromFields: ['id'],
          relationToFields: ['milestoneId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Label',
      dbName: 'labels',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'name',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'color',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'projectId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'project',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Project',
          relationName: 'ProjectLabels',
          relationFromFields: ['projectId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'tasks',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'TaskLabel',
          relationName: 'LabelTaskLabels',
          relationFromFields: ['id'],
          relationToFields: ['labelId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Task',
      dbName: 'tasks',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'title',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'description',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'status',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'priority',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'position',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'dueDate',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'completedAt',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'estimatedHours',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Decimal',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'metadata',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Json',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'updatedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: true,
        },
        {
          name: 'projectId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'assigneeId',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'creatorId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'milestoneId',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'parentId',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'project',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Project',
          relationName: 'ProjectTasks',
          relationFromFields: ['projectId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'assignee',
          kind: 'object',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'User',
          relationName: 'TaskAssignee',
          relationFromFields: ['assigneeId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'creator',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'User',
          relationName: 'TaskCreator',
          relationFromFields: ['creatorId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'milestone',
          kind: 'object',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Milestone',
          relationName: 'MilestoneTasks',
          relationFromFields: ['milestoneId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'parent',
          kind: 'object',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskHierarchy',
          relationFromFields: ['parentId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'subtasks',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskHierarchy',
          relationFromFields: ['id'],
          relationToFields: ['parentId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'comments',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Comment',
          relationName: 'TaskComments',
          relationFromFields: ['id'],
          relationToFields: ['taskId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'labels',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'TaskLabel',
          relationName: 'TaskTaskLabels',
          relationFromFields: ['id'],
          relationToFields: ['taskId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'activities',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Activity',
          relationName: 'TaskActivities',
          relationFromFields: ['id'],
          relationToFields: ['taskId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'attachments',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Attachment',
          relationName: 'TaskAttachments',
          relationFromFields: ['id'],
          relationToFields: ['taskId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'TaskLabel',
      dbName: 'task_labels',
      fields: [
        {
          name: 'taskId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'labelId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'assignedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'task',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskTaskLabels',
          relationFromFields: ['taskId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'label',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Label',
          relationName: 'LabelTaskLabels',
          relationFromFields: ['labelId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: { name: null, fields: ['taskId', 'labelId'] },
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Comment',
      dbName: 'comments',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'content',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'isEdited',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Boolean',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'updatedAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: true,
        },
        {
          name: 'taskId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'authorId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'parentId',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'task',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskComments',
          relationFromFields: ['taskId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'author',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'User',
          relationName: 'UserComments',
          relationFromFields: ['authorId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'parent',
          kind: 'object',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Comment',
          relationName: 'CommentReplies',
          relationFromFields: ['parentId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'replies',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Comment',
          relationName: 'CommentReplies',
          relationFromFields: ['id'],
          relationToFields: ['parentId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'reactions',
          kind: 'object',
          isList: true,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Reaction',
          relationName: 'CommentReactions',
          relationFromFields: ['id'],
          relationToFields: ['commentId'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Reaction',
      dbName: 'reactions',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'emoji',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'commentId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'comment',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Comment',
          relationName: 'CommentReactions',
          relationFromFields: ['commentId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Attachment',
      dbName: 'attachments',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'filename',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'url',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'mimeType',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'size',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'taskId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'task',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskAttachments',
          relationFromFields: ['taskId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Activity',
      dbName: 'activities',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'action',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'details',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Json',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'taskId',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'userId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'task',
          kind: 'object',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Task',
          relationName: 'TaskActivities',
          relationFromFields: ['taskId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'user',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'User',
          relationName: 'UserActivities',
          relationFromFields: ['userId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
    {
      name: 'Notification',
      dbName: 'notifications',
      fields: [
        {
          name: 'id',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: true,
          isId: true,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'type',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'title',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'message',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'String',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'isRead',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'Boolean',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'data',
          kind: 'scalar',
          isList: false,
          isRequired: false,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Json',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'createdAt',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: true,
          type: 'DateTime',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'userId',
          kind: 'scalar',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'Int',
          isGenerated: false,
          isUpdatedAt: false,
        },
        {
          name: 'user',
          kind: 'object',
          isList: false,
          isRequired: true,
          isUnique: false,
          isId: false,
          isReadOnly: false,
          hasDefaultValue: false,
          type: 'User',
          relationName: 'UserNotifications',
          relationFromFields: ['userId'],
          relationToFields: ['id'],
          isGenerated: false,
          isUpdatedAt: false,
        },
      ],
      primaryKey: null,
      uniqueFields: [],
      uniqueIndexes: [],
      isGenerated: false,
    },
  ],
  enums: [],
  types: [],
}
